eval_samples: 1496
hparams: /app/configs/train/allclasses_mcdropout_lossatt_head.yaml
infer_first_frame: 0
infer_folder: /app/datasets/KITTI/testing/image_2/
infer_last_frame: 100
model_dir: /app/models/trained_models/---
saved_model_dir: /app/models/exported_models/---
val_file_pattern: /app/datasets/KITTI/tf/_val.tfrecord
video_path: /app/datasets/videos/---.mp4
