eval_samples: 1000
hparams: /app/efficientdet_uncertainty/configs/train/allclasses_mcdropout_lossatt_BDD_head.yaml
model_dir: /app/efficientdet_uncertainty/models/trained_models/---/
val_file_pattern: /app/efficientdet_uncertainty/datasets/BDD100K/tf_val_split/_val_---.tfrecord
