eval_samples: 453
hparams: /app/configs/train/allclasses_mcdropout_lossatt_BDD_head.yaml
model_dir: /app/models/trained_models/---/
val_file_pattern: /app/datasets/CODA/tf_val_split/bCODA/_val_---.tfrecord
