eval_samples: 1000
hparams: /app/configs/train/allclasses_mcdropout_lossatt_BDD_head.yaml
model_dir: /app/models/trained_models/---/
val_file_pattern: /app/datasets/BDD100K/tf_val_split/_val_---.tfrecord
